### ISSUE TITLE
Roadmap 1.1

### ISSUE THREAD

**Issue by DevLoris** [MdnAgency/prestashop-mdn_blog#1]
# Features

- [x] Add a way to schedule post
- [x] Add sitemap for blog

# Changes

- [x] Remove mandatory thumbnail
- [x] "Blog by MDN" redirecting to categories instead of articles
- [x] New categories or articles no longer hidden
- [x]  Multiple fieldsets for categories
- [x]  Multiple fieldsets for articles

# Bugs

- [x] Fix a crash during installation
- [x] Fix categories not saved on init
